### PR TITLE
Loading and error pages

### PR DESCRIPTION
**Pull request by Tumelo-Mogono-SE**
Created a loading page and then imported suspense inside the layout, home page and recipe details page. The suspsense is used to make the loading page a fallback page while getting data. Inside my loading page, i used the loading spinner component which I renamed in order to not have a conflict with my loading page.

### CODE REVIEW

**Review by ThabangRammitlwa — APPROVED** [review]
Overview
•    Merging from: Loading-and-Error-pages
•    Into: main
•    Number of commits: 17
•    Files changed: 6
Code Review
✓ Code Quality
•    Code follows project style guidelines
•    No redundant or duplicate code
•    Proper error handling implemented
Specific Changes Review
1.    [Imports]
o    Notes: Imported suspense and loading.
2.    Created error handling file
3. Created a loading handler  for the dynamic page
Security Considerations
•    No sensitive data exposed
•    Security best practices followed
•    Dependencies are up to date

**Review by Thapelo08 — APPROVED** [review]
Overview
• Merging from: Loading-and-Error-pages
• Into: main
• Number of commits: 17
• Files changed: 6
Code Review
✓ Code Quality
• No redundant or duplicate code
• Proper error handling implemented
Specific Changes Review

[Imports]
o Notes: Imported suspense and loading.
Created error handling file
Created a loading handler for the dynamic page
Security Considerations
• No sensitive data exposed
• Dependencies are up to date

**Review by TshireletsoRakoma — APPROVED** [review]
Overview
•    Merging from: endpoints
•    Into: main
•    Number of commits: 17
•    Files changed: 6
Code Review
✓ Code Quality
•    Code follows project style guidelines
•    No redundant or duplicate code
•    Proper error handling implemented
Specific Changes Review
[Imports]
o    Notes: Updated imports from 'Loading.js,pages.js,layout.js' to main'
and merged branches
•    No sensitive data exposed
•    Security best practices followed
•    Dependencies are up to date

**Review by Thapeloletsapa — APPROVED** [review]
Overview
•    Merging from: Loading-and-Error-pages
•    Into: main
•    Number of commits: 17
•    Files changed: 6
Code Review
✓ Code Quality
•    Code follows project style guidelines
•    No redundant or duplicate code
•    Proper Loading & error handling implemented
Specific Changes Review

o    Notes: Created a Error handling file, which we will fallback to
o    Notes: Created a loading page and then imported suspense inside the layout, home page and recipe details page
•   No sensitive data exposed 
•   Security best practices followed 
•   Dependencies are up to date

**Pull request merged**
