### PR TITLE
added recipe detail darkmode styles

### PR DESCRIPTION
**Pull request by TapiwaHerbetNosenga**
I changed the tailwind styles on the recipe detail page to work with a darkmode theme

### CODE REVIEW

**Review by Thapelo08 — APPROVED** [review]
Overview
•    Number of commits: 2
•    Files changed: 8
Code Review
✓ Code Quality
•    Code follows project style guidelines
•    No redundant or duplicate code
•    Proper error handling implemented
Specific Changes Review
[Imports]
o    Notes:  added recipe detail darkmode styles
Security Considerations
•    No sensitive data exposed
•    Security best practices followed
•    Dependencies are up to date

**Review by TshireletsoMogwere — APPROVED** [review]
**Overview**
•    Merging from: theme-toggle
•    Into: main
•    Number of commits: 2
•    Files changed: 8

**Code Review**
✓ Code Quality
•    Code follows project style guidelines
•    No redundant or duplicate code
•    Proper error handling implemented

**Specific Changes Review**

- **recipe detail page**
- **components(collapsible section, header, sort control, theme button, recipe, layout & global css**: 
- Notes:  added dark theme colors.

**Security Considerations**
•    No sensitive data exposed
•    Security best practices followed
•    Dependencies are up to date

**Review by KeabetsweMatlhabe — COMMENTED** [review]
Overview
• Merging from: theme-toggle
• Into: main
• Number of commits: 2
• Files changed:8

Specific changes:
 [Theme-toogle]
 - Changed the tailwind styles on the recipe detail page to work with a darkmode theme

**Review by KeabetsweMatlhabe — COMMENTED** [review]
Overview
• Merging from: theme-toggle
• Into: main
• Number of commits: 2
• Files changed:8

Specific changes:
[Theme-toogle]
- Changed the tailwind styles on the recipe detail page to work with a darkmode theme

**Pull request merged**
