### PR TITLE
Fixed the issue of the fetchRecipeById function.

### PR DESCRIPTION
**Pull request by Tumelo-Mogono-SE**
Fixed the URI issue that we forgot to add into the function of fetchRecipeById in order to correctly assess the endpoint.

### CODE REVIEW

**Review by TshireletsoMogwere — APPROVED** [review]
**Pull Request Review**
**Overview**
•    Merging from: deployment
•    Into: main
•    Number of commits: 1
•    Files changed: 1

**Code Review**
Code Quality
-  The code is well structured and easy to read.
-  The changes implemented work as expected.

**Specific Changes Review**
[app/api.js]
o    Notes: modified link that fetches recipe by id.

**Security Considerations**
•    No sensitive data exposed
•    Security best practices followed
•    Dependencies are up to date

**Review by Thapelo08 — APPROVED** [review]
Pull Request Review
Overview
• Merging from: deployment
• Into: main
• Number of commits: 1
• Files changed: 1

Code Review
Code Quality

The code is well structured and easy to read.
The changes implemented work as expected.
Specific Changes Review
[app/api.js]
o Notes: modified link that fetches recipe by id.

Security Considerations
• No sensitive data exposed
• Security best practices followed
• Dependencies are up to date

**Review by TshireletsoRakoma — APPROVED** [review]
Pull Request Review
Overview
• Merging from: deployment
• Into: main
• Number of commits: 1
• Files changed: 1

Code Review
Code Quality

The code is well structured and easy to read.
The changes implemented work as expected.
Specific Changes Review
[app/api.js]
o Notes: modified link that fetches recipe by id.

Security Considerations
• No sensitive data exposed
• Security best practices followed
• Dependencies are up to date

**Review by Thapeloletsapa — APPROVED** [review]
Overview
•    Merging from: deployment
•    Into: main
•    Number of commits: 1
•    Files changed: 1
Code Review
✓ Code Quality
•    Code follows project style guidelines
•    No redundant or duplicate code
•    Proper error handling implemented
Specific Changes Review
o    Notes: Fixed the issue of the fetchRecipeById function.
•    No sensitive data exposed
•    Security best practices followed
•    Dependencies are up to date

**Pull request merged**
